name: Automated quick-and-dirty build

env:
  source-path: src
  isabelle-version: 2021-1
  other-isabelle-repos:
  chapter-name: IOG
  session-name: Thorn_Calculus

on: [push]

jobs:
  quick-and-dirty-build:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest
    steps:
      - name: Get Isabelle from cache if available
        uses: actions/cache@v2
        with:
          key: isabelle-${{ env.isabelle-version }}-linux
          path: /opt/Isabelle${{ env.isabelle-version }}
      - name: Get Isabelle from upstream if not found in cache
        run: |
          if [ ! -e /opt/Isabelle${{ env.isabelle-version }} ]; then
            wget --no-verbose --output-document=- https://mirror.clarkson.edu/isabelle/dist/Isabelle${{ env.isabelle-version }}_linux.tar.gz |
            tar --directory=/opt --extract --gzip
          fi
      - name: Install other Isabelle sessions
        run: |
          mkdir --parent $HOME/.isabelle/Isabelle${{ env.isabelle-version }}
          for repo in ${{ env.other-isabelle-repos }}
          do
            account=`echo $repo | cut --delimiter=/ --fields=1`
            mkdir --parents /opt/other-sessions/$account
            wget --no-verbose --output-document=/opt/other-sessions/$repo.zip https://github.com/$repo/archive/refs/heads/master.zip
            unzip -d /opt/other-sessions/$account /opt/other-sessions/$repo.zip
            echo /opt/other-sessions/$repo-master/${{ env.source-path }} >> $HOME/.isabelle/Isabelle${{ env.isabelle-version }}/ROOTS
          done
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Build
        run: /opt/Isabelle${{ env.isabelle-version }}/bin/isabelle build -o quick_and_dirty -o document=pdf -P output -D ${{ env.source-path }}
      - name: Upload document
        uses: actions/upload-artifact@v2
        with:
          name: document
          path: output/${{ env.chapter-name }}/${{ env.session-name }}/document.pdf
